// ── Items pool ────────────────────────────────────────────────────────────────
const ITEMS = {
  en: [
    // CONCRETE / VISUAL
    "A red barn",
    "A yellow taxi",
    "A green bench",
    "A blue mailbox",
    "A pink flamingo lawn ornament",
    "A white picket fence",
    "A black crow",
    "A brown horse",
    "A gray heron",
    "An orange pumpkin",
    "A purple door",
    "A gold coin",
    "A silver car",
    "A rusty bicycle",
    "A brick chimney",
    "A slate roof",
    "A cobblestone path",
    "A gravel driveway",
    "A metal grate",
    "A wooden wagon",
    "A glass bottle",
    "A ceramic pot",
    "A clay tile",
    "A rope swing",
    "A hammock",
    "A bird bath",
    "A compost bin",
    "A rain barrel",
    "A fire hydrant",
    "A telephone booth",
    "A street sign bent sideways",
    "A traffic cone",
    "A construction crane",
    "A dumpster behind a building",
    "A fire escape",
    "A balcony with flowers",
    "A porch with rocking chairs",
    "A window with a cat sitting in it",
    "A door with a wreath",
    "A staircase leading nowhere",
    "A tunnel",
    "A bridge over dry land",
    "A creek with stepping stones",
    "A pond with lily pads",
    "A fallen log",
    "A stump with rings visible",
    "A rock painted like a ladybug",
    "A piece of trash that looks intentional",
    "A lost glove on a railing",
    "A single shoe on a wire",
    "A broken umbrella",
    "A folding chair set up but empty",
    "A picnic table with chess board drawn on it",
    "A vending machine in an unusual place",
    "A clock showing the wrong time",
    "A number less than 10",
    "A palindrome on a license plate",
    "A word painted on the ground",
    "A heart drawn in dust",
    "A fork in the road with three paths",
    "A circle of stones",
    "A pattern of cracks in pavement",
    "A shadow that looks like an animal",
    "A cloud that looks like something else",
    "A half-eaten apple on a wall",
    "A single ripe berry on a bush",
    "A leaf with holes from insects",
    "A dandelion gone to seed",
    "A four-leaf clover",
    "A snail trail on concrete",
    "A slug on a sidewalk",
    "A beetle on its back",
    "A caterpillar on a stem",
    "A dragonfly perched",
    "A moth on a window screen",
    "A wasp nest under an eave",
    "An anthill",
    "A spider carrying an egg sac",
    "A millipede on a rock",
    "An earthworm after rain",
    "A feather caught in a branch",
    "A bone (maybe from someone's lunch)",
    "An abandoned shoe",
    "A single earring on the ground",
    "A button",
    "A key without a lock",
    "A padlock on a bridge",
    "A coin heads-up",
    "A ticket stub",
    "A bottle cap",
    "A crushed can",
    "A torn photograph",
    "A grocery list dropped on the sidewalk",
    "A note tucked into a crack",
    "A sticker on a street lamp",
    "A chalk drawing on pavement",
    "A handprint in wet cement",
    "A crack in the shape of a continent",
    "A pipe dripping water",
    "A thermostat on an outside wall",
    "A light on during the day",
    "A satellite dish",
    "A chimney with no smoke",
    "A door slightly open",
    "A bright red front door",
    "A blue bicycle",
    "A yellow flower",
    "A purple flower",
    "A white flower",
    "A black cat",
    "A dog larger than a Labrador",
    "A tiny dog",
    "A pine cone",
    "A mushroom",
    "A spider web",
    "A bird's nest",
    "A feather",
    "A butterfly",
    "A bumblebee",
    "A squirrel",
    "A snail",
    "A tree with exposed roots",
    "A tree wider than you can hug",
    "A tree growing through a fence",
    "A building with ivy on it",
    "A building with a red roof",
    "A church tower",
    "A fountain",
    "A statue",
    "A mural or street art piece",
    "A public clock",
    "A footbridge",
    "A stone wall",
    "A wooden fence",
    "A wind chime",
    "A garden gnome",
    "A mailbox that is not red",
    "A flag flying",
    "A parked Tesla",
    "A parked Volvo",
    "A parked motorcycle",
    "A vehicle with stickers",
    "A vehicle older than 20 years",
    "A bench facing water",
    "A bench facing a road",
    "A sign in a foreign language",
    "A number greater than 1000",
    "A locked gate",
    "A ladder",
    "A puddle with a reflection",
    "A reflection in a window",
    "Something perfectly round",
    "Something orange",
    // YOUR FAVORITE...
    "Your favorite tree",
    "Your favorite flower",
    "Your favorite house",
    "Your favorite front door",
    "Your favorite street",
    "Your favorite path",
    "Your favorite bench",
    "Your favorite view",
    "Your favorite bridge",
    "Your favorite garden",
    "Your favorite building",
    "Your favorite window",
    "Your favorite mailbox",
    "Your favorite fence",
    "Your favorite piece of street art",
    "Your favorite statue",
    "Your favorite hidden spot",
    "Your favorite quiet place",
    "Your favorite colorful thing",
    "Your favorite reflection",
    "Your favorite shadow",
    "Your favorite texture",
    "Your favorite old object",
    "Your favorite new object",
    "Your favorite parked vehicle",
    "Your favorite sign",
    "Your favorite rock",
    "Your favorite cloud",
    "Your favorite thing found by accident",
    "Your favorite thing you photographed",
    "Your favorite thing that made you smile",
    "Your favorite thing nobody else notices",
    "Your favorite thing in nature",
    "Your favorite thing made by humans",
    "Your favorite place you would return to",
    // PLAYFUL / WHIMSICAL
    "A very tiny window",
    "A bicycle",
    "A rock that resembles a potato",
    "A cloud that resembles food",
    "A fence that has clearly seen better days",
    "A bench with a questionable view",
    "A mailbox in an unexpected color",
    "A lonely shoe",
    "A lost glove",
    "A pair of lost gloves",
    "A shopping cart where it definitely shouldn't be",
    "A chair outdoors",
    "A chair that nobody seems to use",
    "A sign with too many exclamation marks",
    "A sign that states the obvious",
    "A sign that raises more questions than answers",
    "A door you would never choose",
    "A door you would absolutely choose",
    "A house plant visible through a window",
    "A vehicle with personality",
    "A car older than some players",
    "A vehicle that looks ready for an adventure",
    "A vehicle that looks like it never moves",
    "A garden gnome on duty",
    "A garden decoration that surprises you",
    "A mailbox that looks proud",
    "A fence that is losing the argument with nature",
    "A tree growing somewhere inconvenient",
    "A flower growing somewhere inconvenient",
    "A mushroom that looks important",
    "A very crooked tree",
    "A very straight tree",
    "A bench that deserves an award",
    "A bench you would never sit on",
    "A bird sitting somewhere unusual",
    "A feather in a strange location",
    "A spider web doing excellent work",
    "A puddle worthy of a photograph",
    "A perfectly round stone",
    "A perfectly imperfect stone",
    "A tiny bridge",
    "A giant puddle",
    "A tiny flower",
    "A giant weed",
    "A gate that feels dramatic",
    "A gate that feels unnecessary",
    "A path that looks like a shortcut",
    "A path that definitely is not a shortcut",
    "A staircase to nowhere",
    "A staircase worth climbing",
    "A chimney working hard",
    "A chimney that looks decorative",
    "A window with character",
    "A window that is oddly small",
    "A house with too many decorations",
    "A house with almost no decorations",
    "A tree with multiple trunks",
    "A tree with a hole in it",
    "A branch shaped like something recognizable",
    "A cloud doing its best impression of something",
    "A lamp post that stands out",
    "A lamp post that blends in perfectly",
    "A bicycle basket",
    "A wheelbarrow",
    "A weather vane",
    "A birdhouse",
    "A scarecrow",
    "A fountain that actually works",
    "A number greater than 5000",
    "A public clock showing the wrong time",
    "A shadow that steals the scene",
    "A patch of moss living its best life",
    "A very neat garden",
    "A very chaotic garden",
    "A flower bed with a color theme",
    "A building with an unusual roof",
    "A building painted an unusual color",
    "A red door",
    "A blue door",
    "A yellow door",
    "A purple object",
    "A pink object",
    "A striped object",
    "A polka-dotted object",
    "A heart shape created accidentally",
    "A face hidden in an object",
    "A face hidden in nature",
    // SUBJECTIVE
    "A place you would bring a tourist",
    "A place you would bring on a first date",
    "A place that feels peaceful",
    "A place that feels mysterious",
    "A place that feels forgotten",
    "A place that feels expensive",
    "A place that feels rich in history",
    "A place that feels magical",
    "A place that feels lonely",
    "A place that feels adventurous",
    "A place that feels hidden",
    "A place that feels surprisingly beautiful",
    "A place that deserves more attention",
    "A place you want to revisit",
    "A place you have never noticed before",
    "A place that makes you curious",
    "A place that looks better than it probably is",
    "A place that looks worse than it actually is",
    "A place where you would read a book",
    "A place where you would watch a sunset",
    "A place where you could imagine a movie scene",
    "A place that would make a great album cover",
    "A place that makes you slow down",
    "A hidden spot",
    // ABSTRACT
    "Something that looks like a face",
    "Something that looks like a heart",
    "Something that resembles an animal",
    "Something that resembles a map",
    "Something that represents freedom",
    "Something that represents time",
    "Something that represents luck",
    "Something that represents patience",
    "Something that represents childhood",
    "Something that represents adventure",
    "Something that represents loneliness",
    "Something that represents friendship",
    "Something that represents growth",
    "Something that represents change",
    "Something that represents strength",
    "Something that represents curiosity",
    "Something that represents creativity",
    "Something that represents home",
    "Something that represents the future",
    "Something that represents the past",
    "Something that looks out of place",
    "Something that looks alive but isn't",
    "Something that appears to be moving",
    "Something that looks like it belongs in a fairytale",
    "Something that looks like a secret",
    "Something that looks impossible",
    "Something that looks unfinished",
    "Something that looks ancient",
    "Something that looks brand new",
    "Something that seems to have a story behind it",
    // BEACH / COAST
    "A seashell or pebble worn smooth",
    "A piece of driftwood",
    "A boat or dinghy",
    "A pier or dock",
    "A buoy or mooring ring",
    "A seagull or coastal bird",
    // PEOPLE
    "A person walking a dog",
    "A person on a bicycle",
    "Someone carrying flowers",
    "Someone carrying groceries",
    "A person reading on a bench",
    "A person sitting alone at a cafe table",
    "Someone waiting at a crossing",
    "A person in a bright yellow coat",
    "Someone wearing a hat you would wear",
    "Two people deep in conversation",
    "A group of friends laughing",
    "Someone pushing a stroller",
    "A child running ahead of a parent",
    "Someone taking a photo",
    "A street musician",
    "Someone working outdoors",
    "A postal worker on their route",
    "A jogger",
    "Someone stretching in a park",
    "A person feeding birds",
    "Someone eating on the go",
    "Someone gesturing wildly on the phone",
    "A couple holding hands",
    "Someone dancing, however small the movement",
    "A person in uniform",
    "Someone carrying a very large bag",
    "Someone walking two dogs at once",
    "A person napping in a public place",
    "A crowd waiting for something",
    "A queue outside a shop",
    "Someone sitting on steps",
    "A person's shadow on a wall",
    "A person reflected in a shop window",
    "Your walking companion mid-laugh",
    "A friend pretending to be a statue",
    "A friend photographing something",
    "A friend's shoes on an interesting surface",
    "Your group's shadows together",
    "A friend blending into the scenery",
    "A friend holding something they found",
    "A portrait of a friend in good light",
    "Everyone's hands in one frame",
    "A friend from behind, walking away",
    "The whole group in one frame",
    "A selfie in front of your favorite door",
    "Someone who looks like they are in a hurry",
    "Someone who looks completely unhurried",
    "A stranger whose outfit deserves applause",
    "Someone who looks like a main character",
    "Someone who looks like they know a secret",
    "A stranger doing something kind",
    // NIGHT — kept last on purpose: these only exist after dark, and the
    // theme layer keeps them out of every daytime card.
    "A lit window with the curtains open",
    "A window with a screen flickering behind it",
    "A streetlight with insects circling it",
    "A streetlight that has gone out",
    "The moon between two buildings",
    "A shop sign still glowing after closing",
    "A neon sign missing a letter",
    "Headlights coming towards you",
    "Your shadow cast by a lamp instead of the sun",
    "Two of your shadows at once",
    "A reflection in a dark window",
    "Light spilling out of a doorway",
    "A bicycle light going past",
    "A cat crossing the road",
    "A moth at a lamp",
    "A bat, or something you decide was a bat",
    "A star you can actually see",
    "The blinking light of a plane",
    "A plant on a windowsill, lit from inside",
    "A bus with almost nobody on it",
    "A lit stop with no one waiting",
    "A shop lit up with nobody inside",
    "Someone walking a dog by torchlight",
    "A window where someone is still working",
    "Steam or smoke lit from below",
    "A puddle with a streetlight in it",
    "A building lit a colour it isn't",
    "A sound you cannot place",
    "Music from an open window",
    "A door that looks different after dark",
    "A street you would not recognise in daylight",
    "The last lit window on a street",
    "A place that feels like a film set",
    "A row of parked cars all facing the same way",
    "Your breath in the air",
    "A clock glowing in the dark",
    // SIGNS & WORDS — daylight prompts, so unlike the night block these
    // are free to turn up on a city or architecture card too.
    "A font you would steal",
    "A misspelled sign",
    "A word in a third language",
    "A sign nobody has updated in a decade",
    "A handwritten sign in a window",
    "A sign with a letter missing",
    "A sign that contradicts another sign",
    "An apostrophe in the wrong place",
    "A word you don't know",
    "A shop name that is a pun",
    "A street name you would live on",
    "A number bigger than a hundred",
    "A hand-painted price",
    "A notice taped to a door",
    "A poster for an event that has already passed",
    "An arrow pointing at nothing in particular",
    "Two arrows pointing opposite ways",
    "A plaque nobody reads",
    "A date built into a building",
    "Initials scratched into something",
    "A word in capitals, shouting",
    "A menu written by hand",
    "A sticker with an opinion on it",
    "Graffiti corrected by someone else",
    "A sign mended with tape",
    "A word half worn away",
    "A sign in more than one language",
    "A warning about something unlikely",
    "A crossed-out word",
    "A logo you can't place",
    "Opening hours nobody keeps",
    "The longest word on the street",
  ],
  ru: [
    // КОНКРЕТНОЕ / ВИЗУАЛЬНОЕ
    "Красный амбар",
    "Жёлтое такси",
    "Зелёная скамейка",
    "Синий почтовый ящик",
    "Розовый фламинго на газоне",
    "Белый штакетный забор",
    "Чёрная ворона",
    "Гнедая лошадь",
    "Серая цапля",
    "Оранжевая тыква",
    "Фиолетовая дверь",
    "Золотая монета",
    "Серебристый автомобиль",
    "Ржавый велосипед",
    "Кирпичная труба",
    "Шиферная крыша",
    "Мощёная дорожка",
    "Гравийная дорожка",
    "Металлическая решётка",
    "Деревянная телега",
    "Стеклянная бутылка",
    "Керамический горшок",
    "Черепица",
    "Верёвочные качели",
    "Гамак",
    "Птичья купальня",
    "Компостный ящик",
    "Бочка для дождевой воды",
    "Пожарный гидрант",
    "Телефонная будка",
    "Погнутый дорожный знак",
    "Дорожный конус",
    "Строительный кран",
    "Мусорный контейнер за зданием",
    "Пожарная лестница",
    "Балкон с цветами",
    "Крыльцо с креслами-качалками",
    "Окно с сидящей кошкой",
    "Дверь с венком",
    "Лестница в никуда",
    "Тоннель",
    "Мост над сухой землёй",
    "Ручей с камнями-переправой",
    "Пруд с кувшинками",
    "Упавшее бревно",
    "Пень с видимыми кольцами",
    "Камень, раскрашенный под божью коровку",
    "Мусор, похожий на арт-объект",
    "Потерянная перчатка на перилах",
    "Одинокий ботинок на проводе",
    "Сломанный зонт",
    "Пустой раскладной стул",
    "Пикниковый стол с нарисованной шахматной доской",
    "Торговый автомат в неожиданном месте",
    "Часы, показывающие неверное время",
    "Число меньше 10",
    "Палиндром на номерном знаке",
    "Слово, написанное на земле",
    "Сердце, нарисованное в пыли",
    "Развилка на три дороги",
    "Круг из камней",
    "Узор трещин на асфальте",
    "Тень в форме животного",
    "Облако, похожее на что-то",
    "Надкусанное яблоко на стене",
    "Одинокая спелая ягода на кусте",
    "Лист с дырками от насекомых",
    "Одуванчик с пушинками",
    "Четырёхлистный клевер",
    "След улитки на бетоне",
    "Слизень на тротуаре",
    "Жук на спине",
    "Гусеница на стебле",
    "Стрекоза на ветке",
    "Мотылёк на оконной сетке",
    "Осиное гнездо под карнизом",
    "Муравейник",
    "Паук с коконом",
    "Многоножка на камне",
    "Дождевой червь после дождя",
    "Перо в ветвях",
    "Кость (возможно, от чьего-то обеда)",
    "Брошенный ботинок",
    "Одинокая серёжка на земле",
    "Пуговица",
    "Ключ без замка",
    "Замок на мосту",
    "Монета орлом вверх",
    "Корешок билета",
    "Крышка от бутылки",
    "Смятая банка",
    "Порванная фотография",
    "Брошенный список покупок",
    "Записка в щели стены",
    "Наклейка на фонарном столбе",
    "Рисунок мелом на асфальте",
    "Отпечаток руки в сыром цементе",
    "Трещина в форме континента",
    "Труба, из которой капает вода",
    "Термостат на внешней стене",
    "Свет горит днём",
    "Спутниковая тарелка",
    "Труба без дыма",
    "Приоткрытая дверь",
    "Ярко-красная входная дверь",
    "Синий велосипед",
    "Жёлтый цветок",
    "Фиолетовый цветок",
    "Белый цветок",
    "Чёрный кот",
    "Собака крупнее лабрадора",
    "Крошечная собачка",
    "Еловая шишка",
    "Гриб",
    "Паутина",
    "Птичье гнездо",
    "Перо",
    "Бабочка",
    "Шмель",
    "Белка",
    "Улитка",
    "Дерево с обнажёнными корнями",
    "Дерево, которое не обхватить руками",
    "Дерево, прорастающее сквозь забор",
    "Здание в плюще",
    "Здание с красной крышей",
    "Колокольня",
    "Фонтан",
    "Статуя",
    "Мурал или стрит-арт",
    "Уличные часы",
    "Пешеходный мостик",
    "Каменная стена",
    "Деревянный забор",
    "Ветряной колокольчик",
    "Садовый гном",
    "Почтовый ящик не красного цвета",
    "Развевающийся флаг",
    "Припаркованная Tesla",
    "Припаркованный Volvo",
    "Припаркованный мотоцикл",
    "Машина с наклейками",
    "Автомобиль старше 20 лет",
    "Скамейка у воды",
    "Скамейка у дороги",
    "Вывеска на иностранном языке",
    "Число больше 1000",
    "Закрытые ворота на замок",
    "Лестница",
    "Лужа с отражением",
    "Отражение в окне",
    "Что-то идеально круглое",
    "Что-то оранжевое",
    // ТВОЁ ЛЮБИМОЕ...
    "Твоё любимое дерево",
    "Твой любимый цветок",
    "Твой любимый дом",
    "Твоя любимая входная дверь",
    "Твоя любимая улица",
    "Твоя любимая тропинка",
    "Твоя любимая скамейка",
    "Твой любимый вид",
    "Твой любимый мост",
    "Твой любимый сад",
    "Твоё любимое здание",
    "Твоё любимое окно",
    "Твой любимый почтовый ящик",
    "Твой любимый забор",
    "Твой любимый стрит-арт",
    "Твоя любимая статуя",
    "Твоё любимое скрытое место",
    "Твоё любимое тихое место",
    "Твоя любимая яркая вещь",
    "Твоё любимое отражение",
    "Твоя любимая тень",
    "Твоя любимая текстура",
    "Твой любимый старый предмет",
    "Твой любимый новый предмет",
    "Твой любимый припаркованный транспорт",
    "Твоя любимая вывеска",
    "Твой любимый камень",
    "Твоё любимое облако",
    "Твоя любимая случайная находка",
    "Твоя любимая сфотографированная вещь",
    "Вещь, которая тебя улыбнула",
    "Вещь, которую никто не замечает",
    "Твоё любимое в природе",
    "Твоё любимое творение человека",
    "Место, куда хочется вернуться",
    // ИГРИВОЕ / ОСТРОУМНОЕ
    "Очень маленькое окошко",
    "Велосипед",
    "Камень, похожий на картошку",
    "Облако, похожее на еду",
    "Забор, переживший лучшие времена",
    "Скамейка с сомнительным видом",
    "Почтовый ящик неожиданного цвета",
    "Одинокий ботинок",
    "Потерянная перчатка",
    "Пара потерянных перчаток",
    "Тележка из супермаркета не на месте",
    "Стул на улице",
    "Стул, которым явно не пользуются",
    "Вывеска со слишком многими восклицательными знаками",
    "Вывеска, сообщающая очевидное",
    "Вывеска, порождающая вопросы",
    "Дверь, которую никогда не выберешь",
    "Дверь, которую выберешь непременно",
    "Комнатное растение в окне",
    "Автомобиль с характером",
    "Машина старше некоторых игроков",
    "Транспорт, готовый к приключениям",
    "Транспорт, который, кажется, никогда не трогается",
    "Садовый гном на посту",
    "Садовое украшение, которое удивляет",
    "Почтовый ящик с достоинством",
    "Забор, проигрывающий борьбу с природой",
    "Дерево в неудобном месте",
    "Цветок в неудобном месте",
    "Гриб, выглядящий важно",
    "Очень кривое дерево",
    "Очень прямое дерево",
    "Скамейка, заслуживающая награды",
    "Скамейка, на которую не сядешь",
    "Птица в необычном месте",
    "Перо в странном месте",
    "Паутина, выполненная отлично",
    "Лужа, достойная фотографии",
    "Идеально круглый камень",
    "Неидеально идеальный камень",
    "Крошечный мостик",
    "Огромная лужа",
    "Крошечный цветок",
    "Огромный сорняк",
    "Ворота, полные драматизма",
    "Ворота, которые явно лишние",
    "Тропинка, похожая на срезанный путь",
    "Тропинка, явно не являющаяся срезанным путём",
    "Лестница в никуда",
    "Лестница, на которую стоит подняться",
    "Усердно дымящая труба",
    "Труба-декорация",
    "Окно с характером",
    "Подозрительно маленькое окно",
    "Дом с чрезмерными украшениями",
    "Дом почти без украшений",
    "Дерево с несколькими стволами",
    "Дерево с дуплом",
    "Ветка, напоминающая что-то узнаваемое",
    "Облако, изображающее что-то",
    "Фонарный столб, бросающийся в глаза",
    "Фонарный столб, сливающийся с окружением",
    "Велосипедная корзина",
    "Тачка",
    "Флюгер",
    "Скворечник",
    "Пугало",
    "Фонтан, который работает",
    "Число больше 5000",
    "Уличные часы, показывающие неверное время",
    "Тень, крадущая сцену",
    "Мох, живущий в своё удовольствие",
    "Очень ухоженный сад",
    "Очень хаотичный сад",
    "Клумба с цветовой темой",
    "Здание с необычной крышей",
    "Здание необычного цвета",
    "Красная дверь",
    "Синяя дверь",
    "Жёлтая дверь",
    "Фиолетовый предмет",
    "Розовый предмет",
    "Полосатый предмет",
    "Предмет в горошек",
    "Случайно возникшая форма сердца",
    "Лицо, скрытое в предмете",
    "Лицо, скрытое в природе",
    // СУБЪЕКТИВНОЕ
    "Место, куда привёл бы туриста",
    "Место для первого свидания",
    "Место, где спокойно",
    "Место, которое кажется загадочным",
    "Место, которое кажется забытым",
    "Место, которое выглядит дорого",
    "Место с ощущением истории",
    "Место, которое кажется волшебным",
    "Место, которое кажется одиноким",
    "Место, которое зовёт в приключение",
    "Место, которое кажется скрытым",
    "Место, которое неожиданно прекрасно",
    "Место, заслуживающее внимания",
    "Место, куда хочется вернуться",
    "Место, которое раньше не замечал",
    "Место, которое вызывает любопытство",
    "Место, выглядящее лучше, чем есть",
    "Место, выглядящее хуже, чем есть",
    "Место, где почитал бы книгу",
    "Место, где встретил бы закат",
    "Место для воображаемой киносцены",
    "Место для обложки альбома",
    "Место, где замедляешь шаг",
    "Скрытое место",
    // АБСТРАКТНОЕ
    "Что-то похожее на лицо",
    "Что-то похожее на сердце",
    "Что-то, напоминающее животное",
    "Что-то, напоминающее карту",
    "Что-то, символизирующее свободу",
    "Что-то, символизирующее время",
    "Что-то, символизирующее удачу",
    "Что-то, символизирующее терпение",
    "Что-то, символизирующее детство",
    "Что-то, символизирующее приключение",
    "Что-то, символизирующее одиночество",
    "Что-то, символизирующее дружбу",
    "Что-то, символизирующее рост",
    "Что-то, символизирующее перемены",
    "Что-то, символизирующее силу",
    "Что-то, символизирующее любопытство",
    "Что-то, символизирующее творчество",
    "Что-то, символизирующее дом",
    "Что-то, символизирующее будущее",
    "Что-то, символизирующее прошлое",
    "Что-то не на своём месте",
    "Что-то живое с виду, но не живое",
    "Что-то, кажущееся движущимся",
    "Что-то из сказки",
    "Что-то похожее на секрет",
    "Что-то невозможное",
    "Что-то незаконченное",
    "Что-то, выглядящее очень древним",
    "Что-то совершенно новое",
    "Что-то, за которым чувствуется история",
    // ПЛЯЖ / ПОБЕРЕЖЬЕ
    "Ракушка или гладкий камешок",
    "Кусок морской древесины",
    "Лодка или шлюпка",
    "Пирс или причал",
    "Буй или швартовое кольцо",
    "Чайка или прибрежная птица",
    // ЛЮДИ
    "Человек, выгуливающий собаку",
    "Человек на велосипеде",
    "Кто-то с цветами в руках",
    "Кто-то с пакетами из магазина",
    "Человек, читающий на скамейке",
    "Человек за столиком кафе в одиночестве",
    "Кто-то ждёт на переходе",
    "Человек в ярко-жёлтой куртке",
    "Кто-то в шляпе, которую ты бы носил",
    "Двое, увлечённых разговором",
    "Компания смеющихся друзей",
    "Кто-то с детской коляской",
    "Ребёнок, убежавший вперёд родителей",
    "Кто-то фотографирует",
    "Уличный музыкант",
    "Кто-то работает на улице",
    "Почтальон на маршруте",
    "Бегун",
    "Кто-то разминается в парке",
    "Человек, кормящий птиц",
    "Кто-то ест на ходу",
    "Кто-то бурно жестикулирует по телефону",
    "Пара, держащаяся за руки",
    "Кто-то танцует, пусть даже еле заметно",
    "Человек в форме",
    "Кто-то с очень большой сумкой",
    "Кто-то выгуливает сразу двух собак",
    "Человек, дремлющий в общественном месте",
    "Толпа, которая чего-то ждёт",
    "Очередь у магазина",
    "Кто-то сидит на ступеньках",
    "Чья-то тень на стене",
    "Человек, отражённый в витрине",
    "Твой спутник в момент смеха",
    "Друг, изображающий статую",
    "Друг, который что-то фотографирует",
    "Обувь друга на интересной поверхности",
    "Ваши тени вместе",
    "Друг, сливающийся с пейзажем",
    "Друг с найденной вещью в руках",
    "Портрет друга в хорошем свете",
    "Все руки в одном кадре",
    "Друг со спины, уходящий вдаль",
    "Вся компания в одном кадре",
    "Селфи у твоей любимой двери",
    "Кто-то, кто явно куда-то опаздывает",
    "Кто-то совершенно никуда не спешащий",
    "Незнакомец, чей образ достоин аплодисментов",
    "Кто-то, похожий на главного героя",
    "Кто-то, кто будто знает секрет",
    "Незнакомец, делающий что-то доброе",
    // НОЧЬ
    "Освещённое окно с раскрытыми шторами",
    "Окно, за которым мерцает экран",
    "Фонарь, вокруг которого вьются насекомые",
    "Погасший фонарь",
    "Луна между двумя домами",
    "Вывеска, которая горит после закрытия",
    "Неоновая вывеска с потерянной буквой",
    "Фары, едущие тебе навстречу",
    "Твоя тень от фонаря, а не от солнца",
    "Две твои тени сразу",
    "Отражение в тёмном окне",
    "Свет, льющийся из дверного проёма",
    "Проезжающий мимо велосипедный фонарик",
    "Кошка, перебегающая дорогу",
    "Мотылёк у фонаря",
    "Летучая мышь — или то, что ты решишь ею считать",
    "Звезда, которую и правда видно",
    "Мигающий огонёк самолёта",
    "Растение на подоконнике, подсвеченное изнутри",
    "Автобус, в котором почти никого",
    "Освещённая остановка, где никто не ждёт",
    "Освещённый магазин без единого человека",
    "Кто-то выгуливает собаку с фонариком",
    "Окно, за которым ещё работают",
    "Пар или дым, подсвеченный снизу",
    "Лужа, в которой поместился фонарь",
    "Здание, подсвеченное не своим цветом",
    "Звук, который не получается опознать",
    "Музыка из открытого окна",
    "Дверь, которая в темноте выглядит иначе",
    "Улица, которую не узнать при дневном свете",
    "Последнее горящее окно на улице",
    "Место, похожее на съёмочную площадку",
    "Ряд машин, припаркованных в одну сторону",
    "Твоё дыхание в воздухе",
    "Часы, светящиеся в темноте",
    // ВЫВЕСКИ И СЛОВА
    "Шрифт, который хочется украсть",
    "Вывеска с опечаткой",
    "Слово на третьем языке",
    "Вывеска, которую не обновляли лет десять",
    "Объявление, написанное от руки, в окне",
    "Вывеска, где не хватает буквы",
    "Табличка, спорящая с соседней табличкой",
    "Запятая не на своём месте",
    "Слово, которого ты не знаешь",
    "Название магазина с игрой слов",
    "Название улицы, на которой хотелось бы жить",
    "Число больше ста",
    "Цена, написанная от руки",
    "Объявление, приклеенное к двери",
    "Афиша события, которое уже прошло",
    "Стрелка, указывающая непонятно куда",
    "Две стрелки, показывающие в разные стороны",
    "Табличка, которую никто не читает",
    "Дата, вписанная в здание",
    "Инициалы, нацарапанные на чём-нибудь",
    "Слово, кричащее заглавными буквами",
    "Меню, написанное от руки",
    "Наклейка с чьим-то мнением",
    "Граффити, исправленное кем-то другим",
    "Вывеска, починенная скотчем",
    "Наполовину стёршееся слово",
    "Надпись на нескольких языках",
    "Предупреждение о чём-то маловероятном",
    "Зачёркнутое слово",
    "Логотип, который ты не узнаёшь",
    "Часы работы, которые никто не соблюдает",
    "Самое длинное слово на улице",
  ],
};

/* The index travels: a shared card is nine of these numbers in a link, so
   only ever append to the arrays above — reordering them repoints every
   link anyone has already sent. */
const POOL = ITEMS.en.map((en, index) => ({
  en,
  ru: ITEMS.ru[index],
  index,
}));
