// ── Items pool ────────────────────────────────────────────────────────────────
const ITEMS = {
  en: [
    // CONCRETE / VISUAL
    "A red barn",
    "A yellow taxi",
    "A green bench",
    "A blue mailbox",
    "A pink flamingo lawn ornament",
    "A white picket fence",
    "A black crow",
    "A brown horse",
    "A gray heron",
    "An orange pumpkin",
    "A purple door",
    "A gold coin",
    "A silver car",
    "A rusty bicycle",
    "A brick chimney",
    "A slate roof",
    "A cobblestone path",
    "A gravel driveway",
    "A metal grate",
    "A wooden wagon",
    "A glass bottle",
    "A ceramic pot",
    "A clay tile",
    "A rope swing",
    "A hammock",
    "A bird bath",
    "A compost bin",
    "A rain barrel",
    "A fire hydrant",
    "A telephone booth",
    "A street sign bent sideways",
    "A traffic cone",
    "A construction crane",
    "A dumpster behind a building",
    "A fire escape",
    "A balcony with flowers",
    "A porch with rocking chairs",
    "A window with a cat sitting in it",
    "A door with a wreath",
    "A staircase leading nowhere",
    "A tunnel",
    "A bridge over dry land",
    "A creek with stepping stones",
    "A pond with lily pads",
    "A fallen log",
    "A stump with rings visible",
    "A rock painted like a ladybug",
    "A piece of trash that looks intentional",
    "A lost glove on a railing",
    "A single shoe on a wire",
    "A broken umbrella",
    "A folding chair set up but empty",
    "A picnic table with chess board drawn on it",
    "A vending machine in an unusual place",
    "A clock showing the wrong time",
    "A number less than 10",
    "A palindrome on a license plate",
    "A word painted on the ground",
    "A heart drawn in dust",
    "A fork in the road with three paths",
    "A circle of stones",
    "A pattern of cracks in pavement",
    "A shadow that looks like an animal",
    "A cloud that looks like something else",
    "A half-eaten apple on a wall",
    "A single ripe berry on a bush",
    "A leaf with holes from insects",
    "A dandelion gone to seed",
    "A four-leaf clover",
    "A snail trail on concrete",
    "A slug on a sidewalk",
    "A beetle on its back",
    "A caterpillar on a stem",
    "A dragonfly perched",
    "A moth on a window screen",
    "A wasp nest under an eave",
    "An anthill",
    "A spider carrying an egg sac",
    "A millipede on a rock",
    "An earthworm after rain",
    "A feather caught in a branch",
    "A bone (maybe from someone's lunch)",
    "An abandoned shoe",
    "A single earring on the ground",
    "A button",
    "A key without a lock",
    "A padlock on a bridge",
    "A coin heads-up",
    "A ticket stub",
    "A bottle cap",
    "A crushed can",
    "A torn photograph",
    "A grocery list dropped on the sidewalk",
    "A note tucked into a crack",
    "A sticker on a street lamp",
    "A chalk drawing on pavement",
    "A handprint in wet cement",
    "A crack in the shape of a continent",
    "A pipe dripping water",
    "A thermostat on an outside wall",
    "A light on during the day",
    "A satellite dish",
    "A chimney with no smoke",
    "A door slightly open",
    "A bright red front door",
    "A blue bicycle",
    "A yellow flower",
    "A purple flower",
    "A white flower",
    "A black cat",
    "A dog larger than a Labrador",
    "A tiny dog",
    "A pine cone",
    "A mushroom",
    "A spider web",
    "A bird's nest",
    "A feather",
    "A butterfly",
    "A bumblebee",
    "A squirrel",
    "A snail",
    "A tree with exposed roots",
    "A tree wider than you can hug",
    "A tree growing through a fence",
    "A building with ivy on it",
    "A building with a red roof",
    "A church tower",
    "A fountain",
    "A statue",
    "A mural or street art piece",
    "A public clock",
    "A footbridge",
    "A stone wall",
    "A wooden fence",
    "A wind chime",
    "A garden gnome",
    "A mailbox that is not red",
    "A flag flying",
    "A parked Tesla",
    "A parked Volvo",
    "A parked motorcycle",
    "A vehicle with stickers",
    "A vehicle older than 20 years",
    "A bench facing water",
    "A bench facing a road",
    "A sign in a foreign language",
    "A number greater than 1000",
    "A locked gate",
    "A ladder",
    "A puddle with a reflection",
    "A reflection in a window",
    "Something perfectly round",
    "Something orange",
    // YOUR FAVORITE...
    "Your favorite tree",
    "Your favorite flower",
    "Your favorite house",
    "Your favorite front door",
    "Your favorite street",
    "Your favorite path",
    "Your favorite bench",
    "Your favorite view",
    "Your favorite bridge",
    "Your favorite garden",
    "Your favorite building",
    "Your favorite window",
    "Your favorite mailbox",
    "Your favorite fence",
    "Your favorite piece of street art",
    "Your favorite statue",
    "Your favorite hidden spot",
    "Your favorite quiet place",
    "Your favorite colorful thing",
    "Your favorite reflection",
    "Your favorite shadow",
    "Your favorite texture",
    "Your favorite old object",
    "Your favorite new object",
    "Your favorite parked vehicle",
    "Your favorite sign",
    "Your favorite rock",
    "Your favorite cloud",
    "Your favorite thing found by accident",
    "Your favorite thing you photographed",
    "Your favorite thing that made you smile",
    "Your favorite thing nobody else notices",
    "Your favorite thing in nature",
    "Your favorite thing made by humans",
    "Your favorite place you would return to",
    // PLAYFUL / WHIMSICAL
    "A very tiny window",
    "A bicycle",
    "A rock that resembles a potato",
    "A cloud that resembles food",
    "A fence that has clearly seen better days",
    "A bench with a questionable view",
    "A mailbox in an unexpected color",
    "A lonely shoe",
    "A lost glove",
    "A pair of lost gloves",
    "A shopping cart where it definitely shouldn't be",
    "A chair outdoors",
    "A chair that nobody seems to use",
    "A sign with too many exclamation marks",
    "A sign that states the obvious",
    "A sign that raises more questions than answers",
    "A door you would never choose",
    "A door you would absolutely choose",
    "A house plant visible through a window",
    "A vehicle with personality",
    "A car older than some players",
    "A vehicle that looks ready for an adventure",
    "A vehicle that looks like it never moves",
    "A garden gnome on duty",
    "A garden decoration that surprises you",
    "A mailbox that looks proud",
    "A fence that is losing the argument with nature",
    "A tree growing somewhere inconvenient",
    "A flower growing somewhere inconvenient",
    "A mushroom that looks important",
    "A very crooked tree",
    "A very straight tree",
    "A bench that deserves an award",
    "A bench you would never sit on",
    "A bird sitting somewhere unusual",
    "A feather in a strange location",
    "A spider web doing excellent work",
    "A puddle worthy of a photograph",
    "A perfectly round stone",
    "A perfectly imperfect stone",
    "A tiny bridge",
    "A giant puddle",
    "A tiny flower",
    "A giant weed",
    "A gate that feels dramatic",
    "A gate that feels unnecessary",
    "A path that looks like a shortcut",
    "A path that definitely is not a shortcut",
    "A staircase to nowhere",
    "A staircase worth climbing",
    "A chimney working hard",
    "A chimney that looks decorative",
    "A window with character",
    "A window that is oddly small",
    "A house with too many decorations",
    "A house with almost no decorations",
    "A tree with multiple trunks",
    "A tree with a hole in it",
    "A branch shaped like something recognizable",
    "A cloud doing its best impression of something",
    "A lamp post that stands out",
    "A lamp post that blends in perfectly",
    "A bicycle basket",
    "A wheelbarrow",
    "A weather vane",
    "A birdhouse",
    "A scarecrow",
    "A fountain that actually works",
    "A number greater than 5000",
    "A public clock showing the wrong time",
    "A shadow that steals the scene",
    "A patch of moss living its best life",
    "A very neat garden",
    "A very chaotic garden",
    "A flower bed with a color theme",
    "A building with an unusual roof",
    "A building painted an unusual color",
    "A red door",
    "A blue door",
    "A yellow door",
    "A purple object",
    "A pink object",
    "A striped object",
    "A polka-dotted object",
    "A heart shape created accidentally",
    "A face hidden in an object",
    "A face hidden in nature",
    // SUBJECTIVE
    "A place you would bring a tourist",
    "A place you would bring on a first date",
    "A place that feels peaceful",
    "A place that feels mysterious",
    "A place that feels forgotten",
    "A place that feels expensive",
    "A place that feels rich in history",
    "A place that feels magical",
    "A place that feels lonely",
    "A place that feels adventurous",
    "A place that feels hidden",
    "A place that feels surprisingly beautiful",
    "A place that deserves more attention",
    "A place you want to revisit",
    "A place you have never noticed before",
    "A place that makes you curious",
    "A place that looks better than it probably is",
    "A place that looks worse than it actually is",
    "A place where you would read a book",
    "A place where you would watch a sunset",
    "A place where you could imagine a movie scene",
    "A place that would make a great album cover",
    "A place that makes you slow down",
    "A hidden spot",
    // ABSTRACT
    "Something that looks like a face",
    "Something that looks like a heart",
    "Something that resembles an animal",
    "Something that resembles a map",
    "Something that represents freedom",
    "Something that represents time",
    "Something that represents luck",
    "Something that represents patience",
    "Something that represents childhood",
    "Something that represents adventure",
    "Something that represents loneliness",
    "Something that represents friendship",
    "Something that represents growth",
    "Something that represents change",
    "Something that represents strength",
    "Something that represents curiosity",
    "Something that represents creativity",
    "Something that represents home",
    "Something that represents the future",
    "Something that represents the past",
    "Something that looks out of place",
    "Something that looks alive but isn't",
    "Something that appears to be moving",
    "Something that looks like it belongs in a fairytale",
    "Something that looks like a secret",
    "Something that looks impossible",
    "Something that looks unfinished",
    "Something that looks ancient",
    "Something that looks brand new",
    "Something that seems to have a story behind it",
    // BEACH / COAST
    "A seashell or pebble worn smooth",
    "A piece of driftwood",
    "A boat or dinghy",
    "A pier or dock",
    "A buoy or mooring ring",
    "A seagull or coastal bird",
  ],
  ru: [
    // КОНКРЕТНОЕ / ВИЗУАЛЬНОЕ
    "Красный амбар",
    "Жёлтое такси",
    "Зелёная скамейка",
    "Синий почтовый ящик",
    "Розовый фламинго на газоне",
    "Белый штакетный забор",
    "Чёрная ворона",
    "Гнедая лошадь",
    "Серая цапля",
    "Оранжевая тыква",
    "Фиолетовая дверь",
    "Золотая монета",
    "Серебристый автомобиль",
    "Ржавый велосипед",
    "Кирпичная труба",
    "Шиферная крыша",
    "Мощёная дорожка",
    "Гравийная дорожка",
    "Металлическая решётка",
    "Деревянная телега",
    "Стеклянная бутылка",
    "Керамический горшок",
    "Черепица",
    "Верёвочные качели",
    "Гамак",
    "Птичья купальня",
    "Компостный ящик",
    "Бочка для дождевой воды",
    "Пожарный гидрант",
    "Телефонная будка",
    "Погнутый дорожный знак",
    "Дорожный конус",
    "Строительный кран",
    "Мусорный контейнер за зданием",
    "Пожарная лестница",
    "Балкон с цветами",
    "Крыльцо с креслами-качалками",
    "Окно с сидящей кошкой",
    "Дверь с венком",
    "Лестница в никуда",
    "Тоннель",
    "Мост над сухой землёй",
    "Ручей с камнями-переправой",
    "Пруд с кувшинками",
    "Упавшее бревно",
    "Пень с видимыми кольцами",
    "Камень, раскрашенный под божью коровку",
    "Мусор, похожий на арт-объект",
    "Потерянная перчатка на перилах",
    "Одинокий ботинок на проводе",
    "Сломанный зонт",
    "Пустой раскладной стул",
    "Пикниковый стол с нарисованной шахматной доской",
    "Торговый автомат в неожиданном месте",
    "Часы, показывающие неверное время",
    "Число меньше 10",
    "Палиндром на номерном знаке",
    "Слово, написанное на земле",
    "Сердце, нарисованное в пыли",
    "Развилка на три дороги",
    "Круг из камней",
    "Узор трещин на асфальте",
    "Тень в форме животного",
    "Облако, похожее на что-то",
    "Надкусанное яблоко на стене",
    "Одинокая спелая ягода на кусте",
    "Лист с дырками от насекомых",
    "Одуванчик с пушинками",
    "Четырёхлистный клевер",
    "След улитки на бетоне",
    "Слизень на тротуаре",
    "Жук на спине",
    "Гусеница на стебле",
    "Стрекоза на ветке",
    "Мотылёк на оконной сетке",
    "Осиное гнездо под карнизом",
    "Муравейник",
    "Паук с коконом",
    "Многоножка на камне",
    "Дождевой червь после дождя",
    "Перо в ветвях",
    "Кость (возможно, от чьего-то обеда)",
    "Брошенный ботинок",
    "Одинокая серёжка на земле",
    "Пуговица",
    "Ключ без замка",
    "Замок на мосту",
    "Монета орлом вверх",
    "Корешок билета",
    "Крышка от бутылки",
    "Смятая банка",
    "Порванная фотография",
    "Брошенный список покупок",
    "Записка в щели стены",
    "Наклейка на фонарном столбе",
    "Рисунок мелом на асфальте",
    "Отпечаток руки в сыром цементе",
    "Трещина в форме континента",
    "Труба, из которой капает вода",
    "Термостат на внешней стене",
    "Свет горит днём",
    "Спутниковая тарелка",
    "Труба без дыма",
    "Приоткрытая дверь",
    "Ярко-красная входная дверь",
    "Синий велосипед",
    "Жёлтый цветок",
    "Фиолетовый цветок",
    "Белый цветок",
    "Чёрный кот",
    "Собака крупнее лабрадора",
    "Крошечная собачка",
    "Еловая шишка",
    "Гриб",
    "Паутина",
    "Птичье гнездо",
    "Перо",
    "Бабочка",
    "Шмель",
    "Белка",
    "Улитка",
    "Дерево с обнажёнными корнями",
    "Дерево, которое не обхватить руками",
    "Дерево, прорастающее сквозь забор",
    "Здание в плюще",
    "Здание с красной крышей",
    "Колокольня",
    "Фонтан",
    "Статуя",
    "Мурал или стрит-арт",
    "Уличные часы",
    "Пешеходный мостик",
    "Каменная стена",
    "Деревянный забор",
    "Ветряной колокольчик",
    "Садовый гном",
    "Почтовый ящик не красного цвета",
    "Развевающийся флаг",
    "Припаркованная Tesla",
    "Припаркованный Volvo",
    "Припаркованный мотоцикл",
    "Машина с наклейками",
    "Автомобиль старше 20 лет",
    "Скамейка у воды",
    "Скамейка у дороги",
    "Вывеска на иностранном языке",
    "Число больше 1000",
    "Закрытые ворота на замок",
    "Лестница",
    "Лужа с отражением",
    "Отражение в окне",
    "Что-то идеально круглое",
    "Что-то оранжевое",
    // ТВОЁ ЛЮБИМОЕ...
    "Твоё любимое дерево",
    "Твой любимый цветок",
    "Твой любимый дом",
    "Твоя любимая входная дверь",
    "Твоя любимая улица",
    "Твоя любимая тропинка",
    "Твоя любимая скамейка",
    "Твой любимый вид",
    "Твой любимый мост",
    "Твой любимый сад",
    "Твоё любимое здание",
    "Твоё любимое окно",
    "Твой любимый почтовый ящик",
    "Твой любимый забор",
    "Твой любимый стрит-арт",
    "Твоя любимая статуя",
    "Твоё любимое скрытое место",
    "Твоё любимое тихое место",
    "Твоя любимая яркая вещь",
    "Твоё любимое отражение",
    "Твоя любимая тень",
    "Твоя любимая текстура",
    "Твой любимый старый предмет",
    "Твой любимый новый предмет",
    "Твой любимый припаркованный транспорт",
    "Твоя любимая вывеска",
    "Твой любимый камень",
    "Твоё любимое облако",
    "Твоя любимая случайная находка",
    "Твоя любимая сфотографированная вещь",
    "Вещь, которая тебя улыбнула",
    "Вещь, которую никто не замечает",
    "Твоё любимое в природе",
    "Твоё любимое творение человека",
    "Место, куда хочется вернуться",
    // ИГРИВОЕ / ОСТРОУМНОЕ
    "Очень маленькое окошко",
    "Велосипед",
    "Камень, похожий на картошку",
    "Облако, похожее на еду",
    "Забор, переживший лучшие времена",
    "Скамейка с сомнительным видом",
    "Почтовый ящик неожиданного цвета",
    "Одинокий ботинок",
    "Потерянная перчатка",
    "Пара потерянных перчаток",
    "Тележка из супермаркета не на месте",
    "Стул на улице",
    "Стул, которым явно не пользуются",
    "Вывеска со слишком многими восклицательными знаками",
    "Вывеска, сообщающая очевидное",
    "Вывеска, порождающая вопросы",
    "Дверь, которую никогда не выберешь",
    "Дверь, которую выберешь непременно",
    "Комнатное растение в окне",
    "Автомобиль с характером",
    "Машина старше некоторых игроков",
    "Транспорт, готовый к приключениям",
    "Транспорт, который, кажется, никогда не трогается",
    "Садовый гном на посту",
    "Садовое украшение, которое удивляет",
    "Почтовый ящик с достоинством",
    "Забор, проигрывающий борьбу с природой",
    "Дерево в неудобном месте",
    "Цветок в неудобном месте",
    "Гриб, выглядящий важно",
    "Очень кривое дерево",
    "Очень прямое дерево",
    "Скамейка, заслуживающая награды",
    "Скамейка, на которую не сядешь",
    "Птица в необычном месте",
    "Перо в странном месте",
    "Паутина, выполненная отлично",
    "Лужа, достойная фотографии",
    "Идеально круглый камень",
    "Неидеально идеальный камень",
    "Крошечный мостик",
    "Огромная лужа",
    "Крошечный цветок",
    "Огромный сорняк",
    "Ворота, полные драматизма",
    "Ворота, которые явно лишние",
    "Тропинка, похожая на срезанный путь",
    "Тропинка, явно не являющаяся срезанным путём",
    "Лестница в никуда",
    "Лестница, на которую стоит подняться",
    "Усердно дымящая труба",
    "Труба-декорация",
    "Окно с характером",
    "Подозрительно маленькое окно",
    "Дом с чрезмерными украшениями",
    "Дом почти без украшений",
    "Дерево с несколькими стволами",
    "Дерево с дуплом",
    "Ветка, напоминающая что-то узнаваемое",
    "Облако, изображающее что-то",
    "Фонарный столб, бросающийся в глаза",
    "Фонарный столб, сливающийся с окружением",
    "Велосипедная корзина",
    "Тачка",
    "Флюгер",
    "Скворечник",
    "Пугало",
    "Фонтан, который работает",
    "Число больше 5000",
    "Уличные часы, показывающие неверное время",
    "Тень, крадущая сцену",
    "Мох, живущий в своё удовольствие",
    "Очень ухоженный сад",
    "Очень хаотичный сад",
    "Клумба с цветовой темой",
    "Здание с необычной крышей",
    "Здание необычного цвета",
    "Красная дверь",
    "Синяя дверь",
    "Жёлтая дверь",
    "Фиолетовый предмет",
    "Розовый предмет",
    "Полосатый предмет",
    "Предмет в горошек",
    "Случайно возникшая форма сердца",
    "Лицо, скрытое в предмете",
    "Лицо, скрытое в природе",
    // СУБЪЕКТИВНОЕ
    "Место, куда привёл бы туриста",
    "Место для первого свидания",
    "Место, где спокойно",
    "Место, которое кажется загадочным",
    "Место, которое кажется забытым",
    "Место, которое выглядит дорого",
    "Место с ощущением истории",
    "Место, которое кажется волшебным",
    "Место, которое кажется одиноким",
    "Место, которое зовёт в приключение",
    "Место, которое кажется скрытым",
    "Место, которое неожиданно прекрасно",
    "Место, заслуживающее внимания",
    "Место, куда хочется вернуться",
    "Место, которое раньше не замечал",
    "Место, которое вызывает любопытство",
    "Место, выглядящее лучше, чем есть",
    "Место, выглядящее хуже, чем есть",
    "Место, где почитал бы книгу",
    "Место, где встретил бы закат",
    "Место для воображаемой киносцены",
    "Место для обложки альбома",
    "Место, где замедляешь шаг",
    "Скрытое место",
    // АБСТРАКТНОЕ
    "Что-то похожее на лицо",
    "Что-то похожее на сердце",
    "Что-то, напоминающее животное",
    "Что-то, напоминающее карту",
    "Что-то, символизирующее свободу",
    "Что-то, символизирующее время",
    "Что-то, символизирующее удачу",
    "Что-то, символизирующее терпение",
    "Что-то, символизирующее детство",
    "Что-то, символизирующее приключение",
    "Что-то, символизирующее одиночество",
    "Что-то, символизирующее дружбу",
    "Что-то, символизирующее рост",
    "Что-то, символизирующее перемены",
    "Что-то, символизирующее силу",
    "Что-то, символизирующее любопытство",
    "Что-то, символизирующее творчество",
    "Что-то, символизирующее дом",
    "Что-то, символизирующее будущее",
    "Что-то, символизирующее прошлое",
    "Что-то не на своём месте",
    "Что-то живое с виду, но не живое",
    "Что-то, кажущееся движущимся",
    "Что-то из сказки",
    "Что-то похожее на секрет",
    "Что-то невозможное",
    "Что-то незаконченное",
    "Что-то, выглядящее очень древним",
    "Что-то совершенно новое",
    "Что-то, за которым чувствуется история",
    // ПЛЯЖ / ПОБЕРЕЖЬЕ
    "Ракушка или гладкий камешок",
    "Кусок морской древесины",
    "Лодка или шлюпка",
    "Пирс или причал",
    "Буй или швартовое кольцо",
    "Чайка или прибрежная птица",
  ],
};

const POOL = ITEMS.en.map((en, index) => ({
  en,
  ru: ITEMS.ru[index],
}));
